/*
 * bcconformer_v3 inference for the Amaze keyword.
 *
 * Port of models/models.py :: BCConformerV3. Input is the (49, 40) log-mel
 * produced by kws_frontend.h; output is P(keyword) in [0, 1].
 *
 * WEIGHTS
 * -------
 * Weights live in flash as one flat int8 blob plus one float32 scale per
 * tensor. Every tensor with two or more axes is stored with its axes reversed,
 * which is what puts the reduction axis of each kernel adjacent in memory so
 * the INT8 kernels in kws_int8.h can consume it. tools/export_weights.py owns
 * that rule and kws_model_data.h describes the result; nothing here transposes
 * anything at runtime.
 *
 * A second, float32 blob in the identical layout exists only so the host
 * harness can measure what the INT8 weights cost numerically. It is not built
 * into the firmware.
 */

#ifndef KWS_MODEL_H
#define KWS_MODEL_H

#include <stddef.h>
#include <stdint.h>

#include "kws_frontend.h"

#define KWS_DIM     48    /* conformer width            */
#define KWS_HEADS   4
#define KWS_HEAD_DIM (KWS_DIM / KWS_HEADS)
#define KWS_C1_OUT  32    /* stem width after conv1     */
#define KWS_C2_OUT  48    /* stem width after conv2     */
#define KWS_STEM_MELS 10  /* mel bins after the stride  */
#define KWS_BLOCKS  3
#define KWS_SE      ((KWS_DIM / 8) > 4 ? (KWS_DIM / 8) : 4)   /* 6 */
#define KWS_POOL_HIDDEN 24
#define KWS_FEAT    (2 * KWS_DIM + 1)                          /* 97 */

/* Tensors per RelConformerBlock, in the order they appear in models.py:
 *   0,1  LayerNorm scale,bias
 *   2,3  qkv Dense kernel,bias
 *   4    relative position bias (2*FRAMES-1, HEADS)
 *   5,6  attention output Dense kernel,bias
 *   7,8  LayerNorm scale,bias
 *   9    depthwise k=3
 *   10   depthwise k=7
 *   11   pointwise 1x1
 *   12   SE reduce
 *   13   SE expand
 *   14,15 LayerNorm scale,bias
 *   16,17 FFN in  Dense kernel,bias
 *   18,19 FFN out Dense kernel,bias
 */
#define KWS_BLOCK_TENSORS 20

enum {
    KWS_T_CONV1     = 0,
    KWS_T_GN1_SCALE = 1,
    KWS_T_GN1_BIAS  = 2,
    KWS_T_FCONV     = 3,
    KWS_T_GN2_SCALE = 4,
    KWS_T_GN2_BIAS  = 5,
    KWS_T_CONV2     = 6,
    KWS_T_GN3_SCALE = 7,
    KWS_T_GN3_BIAS  = 8,
    KWS_T_MEL_GATE  = 9,
    KWS_T_BLOCKS    = 10,                       /* 3 * 20 */
    KWS_T_POOL_PROJ = KWS_T_BLOCKS + KWS_BLOCKS * KWS_BLOCK_TENSORS,   /* 70 */
    KWS_T_POOL_BIAS = 71,
    KWS_T_OR_W      = 72,
    KWS_T_OR_B      = 73,
    KWS_T_HEAD_K    = 74,
    KWS_T_HEAD_B    = 75,
    KWS_NUM_TENSORS = 76
};

typedef struct {
    int32_t  dim0, dim1, dim2, dim3;
    uint32_t count;      /* elements                                  */
    uint32_t offset;     /* byte offset into kws_blob_i8, 0xFFFF if float */
    uint32_t foff;       /* element offset into kws_blob_f32           */
} kws_tensor_meta;

extern const kws_tensor_meta kws_tensors[KWS_NUM_TENSORS];

/*
 * The weight blob. The arrays themselves are generated by tools/bin2c.py, which
 * guarantees 16-byte alignment: the Xtensa LX7 traps on unaligned loads, so a
 * blob placed into .rodata by the assembler would be unsafe.
 *
 * Non-const pointers to const data so the host harness can rebind them to heap
 * copies; the firmware binds them to the generated arrays. Both link the same
 * inference code, so a host pass is a real pass.
 */
extern const int8_t *kws_blob_i8;
extern const float  *kws_blob_f32;   /* NULL in firmware; host A/B only */

/* Mirrors KWS_PARAM_COUNT and KWS_I8_BYTES from the generated table, which only
 * kws_model.c includes. Having them here keeps callers from instantiating that
 * table a second time and colliding with the linker. */
#ifndef KWS_PARAM_COUNT
#define KWS_PARAM_COUNT 84865u
#endif
#ifndef KWS_I8_BYTES
#define KWS_I8_BYTES 80624u
#endif

void kws_model_init(void);

/*
 * Measure the fast exp against the library's and enable it if it is accurate
 * enough (1e-4 relative over [-30, 30]). Returns 1 if the fast path is in use;
 * if it returns 0 the model falls back to expf, which is slower but correct.
 * kws_expf_worst_relerr() reports what was measured either way.
 */
int kws_expf_selftest(void);
float kws_expf_worst_relerr(void);

/* The same contract for the reciprocal swish needs: measured against 1.0f/d
 * over every divisor the model produces, 1e-6 relative, with the division left
 * in place if it misses. kws_rcp_worst_relerr() reports what was measured. */
int kws_rcp_selftest(void);
float kws_rcp_worst_relerr(void);

/* The reciprocal square root the two norms use, gated by the same verdict as the
 * reciprocal because it shares its seed. */
float kws_rsqrt_worst_relerr(void);

/* Run the network. `spec` is [KWS_FRAMES][KWS_MELS] row-major. */
float kws_model_run(const float *spec);

/*
 * The model split at the only clean seam: kws_model_front() reduces the
 * spectrogram to the 49x48 the conformer stack consumes and writes it to the
 * shared s_seq; kws_model_back() reads s_seq and returns the probability.
 *
 * kws_model_run() is exactly these two in sequence, and that is what the host
 * harness measures, so a parity number here describes the arithmetic both paths
 * execute. The firmware uses the split form to run the halves on separate cores:
 * the halves share no buffer except s_seq, which is the handoff, so one binary
 * semaphore per direction is the whole of the synchronisation.
 *
 * s_seq must not be touched between the two calls except by handing it over.
 */
void kws_model_front(const float *spec);
float kws_model_back(void);

/*
 * Replace the INT8 weights with the float32 ones for one run, so the harness can
 * measure what the quantised weights cost from a single code path. 0 is the
 * firmware setting. Returns the previous mode.
 */
int kws_model_set_float_weights(int on);

/* Name of the fixture being run, so a traced build can label its dumps.
 * Diagnostics only; it has no effect on the result. */
void kws_model_set_tag(const char *tag);

/* Inference time in microseconds for the most recent run, and the total for
 * every run since boot. The firmware prints these; they are the only honest
 * answer to the CPU budget question. */
uint32_t kws_model_last_us(void);
uint64_t kws_model_total_us(void);

/*
 * Per-stage cost, accumulated across runs since the last reset. An inference
 * that overruns the hop needs to be attacked where the time actually goes, and
 * "the model is slow" is not an argument: the whole forward pass is 11 MMAC,
 * which is milliseconds of work on a part with a dot-product-less MAC, so a
 * stage that costs five times its share is a bug in that stage.
 *
 * KWS_STAGE_COUNT slots, in execution order. kws_model_stage_name() gives the
 * label, kws_model_stage_us() the accumulated microseconds, and
 * kws_model_stage_runs() how many runs have contributed.
 */
#define KWS_STAGE_COUNT 9
const char *kws_model_stage_name(int slot);
uint64_t kws_model_stage_us(int slot);
uint64_t kws_model_stage_runs(void);
void kws_model_stage_reset(void);

#endif /* KWS_MODEL_H */