/*
 * bcconformer_v3 inference for the Amaze keyword.
 *
 * Port of models/models.py :: BCConformerV3. Input is the (49, 40) log-mel
 * produced by kws_frontend.h; output is P(keyword) in [0, 1].
 *
 * Weights live in flash as one flat float32 blob. The generated header
 * (kws_model.h) describes it as an array of kws_tensor_meta so tensors are
 * addressed by compile-time index, never by string.
 */

#ifndef KWS_MODEL_H
#define KWS_MODEL_H

#include <stddef.h>
#include <stdint.h>

#include "kws_frontend.h"

#define KWS_DIM     48    /* conformer width            */
#define KWS_HEADS   4
#define KWS_HEAD_DIM (KWS_DIM / KWS_HEADS)
#define KWS_C1_OUT  32    /* stem width after conv1     */
#define KWS_C2_OUT  48    /* stem width after conv2     */
#define KWS_STEM_MELS 10  /* mel bins after the stride  */
#define KWS_BLOCKS  3
#define KWS_SE      ((KWS_DIM / 8) > 4 ? (KWS_DIM / 8) : 4)   /* 6 */
#define KWS_POOL_HIDDEN 24
#define KWS_FEAT    (2 * KWS_DIM + 1)                          /* 97 */

/* Tensors per RelConformerBlock, in the order they appear in models.py:
 *   0,1  LayerNorm scale,bias
 *   2,3  qkv Dense kernel,bias
 *   4    relative position bias (2*FRAMES-1, HEADS)
 *   5,6  attention output Dense kernel,bias
 *   7,8  LayerNorm scale,bias
 *   9    depthwise k=3
 *   10   depthwise k=7
 *   11   pointwise 1x1
 *   12   SE reduce
 *   13   SE expand
 *   14,15 LayerNorm scale,bias
 *   16,17 FFN in  Dense kernel,bias
 *   18,19 FFN out Dense kernel,bias
 */
#define KWS_BLOCK_TENSORS 20

enum {
    KWS_T_CONV1     = 0,
    KWS_T_GN1_SCALE = 1,
    KWS_T_GN1_BIAS  = 2,
    KWS_T_FCONV     = 3,
    KWS_T_GN2_SCALE = 4,
    KWS_T_GN2_BIAS  = 5,
    KWS_T_CONV2     = 6,
    KWS_T_GN3_SCALE = 7,
    KWS_T_GN3_BIAS  = 8,
    KWS_T_MEL_GATE  = 9,
    KWS_T_BLOCKS    = 10,                       /* 3 * 20 */
    KWS_T_POOL_PROJ = KWS_T_BLOCKS + KWS_BLOCKS * KWS_BLOCK_TENSORS,   /* 70 */
    KWS_T_POOL_BIAS = 71,
    KWS_T_OR_W      = 72,
    KWS_T_OR_B      = 73,
    KWS_T_HEAD_K    = 74,
    KWS_T_HEAD_B    = 75,
    KWS_NUM_TENSORS = 76
};

typedef struct {
    int32_t  dim0, dim1, dim2, dim3;
    uint32_t count, offset;     /* offset in float32 elements */
} kws_tensor_meta;

extern const kws_tensor_meta kws_tensors[KWS_NUM_TENSORS];

/*
 * The weight blob. The array itself is generated by tools/bin2c.py, which
 * guarantees 16-byte alignment (the Xtensa LX7 traps on unaligned float
 * loads, so a plain embedded binary would be unsafe).
 *
 * Non-const pointer to const data so the host test can rebind it to a heap
 * copy; the firmware binds it to the generated array. Both link the same
 * inference code, so a host pass is a real pass.
 */
extern const float *kws_blob;

#define W(idx) (kws_blob + kws_tensors[(idx)].offset)

/* Mirrors KWS_PARAM_COUNT from the generated table, which only kws_model.c
 * includes. Having it here keeps callers from instantiating that table a
 * second time and colliding with the linker. */
#ifndef KWS_PARAM_COUNT
#define KWS_PARAM_COUNT 84865u
#endif

void kws_model_init(void);

/* Run the network. `spec` is [KWS_FRAMES][KWS_MELS] row-major. */
float kws_model_run(const float *spec);

#ifdef KWS_HOST_TEST
/*
 * Validation hooks. Setting kws_debug_stage to a non-zero value makes the
 * forward pass copy the named intermediate into kws_debug_buf after that stage,
 * so the host harness can bisect a numeric mismatch against the JAX reference
 * layer by layer instead of guessing. kws_debug_stage is 0 in normal firmware
 * operation and the comparisons are single branches, so the cost is nil.
 *
 * Stages:
 *   1  stem output h            (49, 20, 32)  after GN1/GN2 + bcast add
 *   2  conv2 raw output         (49, 10, 48)
 *   3  conv2 after GN3 + swish  (49, 10, 48)
 *   4  seq after the mel gate   (49, 48)
 *   5,6,7  seq after block 1,2,3 (49, 48)
 *   8  pooled feature vector    (97)
 */
extern volatile int    kws_debug_stage;
extern volatile size_t kws_debug_n;
extern float           kws_debug_buf[];

#define KWS_DEBUG_MAX 32768

/* Isolation hook: expose build_feat() so the host test can validate the delta
 * stack on its own, instead of inferring it from a downstream conv1 mismatch. */
void kws_debug_build_feat(const float *spec, int t, float *out /* 3 x 120 */);
void kws_debug_conv1(const float *spec, int t, float *out /* 20 x 32 */);

/* Report the addresses of the static activation buffers, so an overlap shows up
 * as a numeric fact instead of a mystery divergence between two code paths. */
void kws_debug_addrs(const char **names, const void **ptrs, int n);
#endif

#endif /* KWS_MODEL_H */