/*
 * Public interface of the Amaze log-mel front end.
 *
 * The feature contract is fixed by models/features.py:
 * 49 frames x 40 mels from a 1.000 s window at 16 kHz. Any change here must be
 * mirrored in that file, or the network receives features it was never trained
 * on.
 */

#ifndef KWS_FRONTEND_H
#define KWS_FRONTEND_H

#include <stdbool.h>
#include <stdint.h>

#define KWS_SAMPLE_RATE  16000
#define KWS_NFFT         512
#define KWS_WIN          480
#define KWS_HOP          320
#define KWS_MELS         40
#define KWS_FRAMES       49
#define KWS_AUDIO_SAMPLES 16000

/* Largest walk the window can absorb in one update. Chosen as a whole number
 * of feature hops so frame reuse is exact; kws_frontend_step rejects
 * incompatible sizes. 3200 samples = 200 ms. */
#define KWS_MAX_HOP      3200

/* Generated by tools/export_weights.py from numpy so the window and the
 * filterbank are bit-comparable with the Python training pipeline. */
typedef struct {
    int16_t start;   /* first FFT bin touched by this mel filter */
    int16_t n;       /* number of bins / weights */
} kws_mel_span;

extern const float     kws_window[KWS_WIN];
extern const kws_mel_span kws_mel_spans[KWS_MELS];
extern const float     kws_mel_weights[];   /* packed, offsets in kws_mel_span */

bool kws_frontend_init(void);
void kws_frontend_reset(void);

/* Append n new samples (n <= KWS_MAX_HOP). */
void kws_frontend_push(const int16_t *samples, int n);

/*
 * Write the current 49x40 log-mel into out.
 * Returns false until KWS_AUDIO_SAMPLES have been accumulated.
 */
bool kws_frontend_compute(float *out);

/* True once at least one full window has been emitted. */
bool kws_frontend_primed(void);

#endif /* KWS_FRONTEND_H */