/* Generated by tools/export_weights.py - do not edit by hand.
 * Source: models/best_v11_production.flax  arch bcconformer_v3  84,865 params
 *
 * Emits the tensor table only. The enum, kws_tensor_meta and the
 * kws_blob declaration are owned by kws_model.h, which must be
 * included before this file. The index of each entry here matches
 * the enum in kws_model.h; a build-time assert below enforces it.
 */
#pragma once

#define KWS_BLOB_FLOATS 84865u
#define KWS_PARAM_COUNT  84865u

const kws_tensor_meta kws_tensors[] = {
    /* Conv_0/kernel                                        */ { 3, 3, 3, 32, 864u, 0u },
    /* GroupNorm_0/scale                                    */ { 32, 1, 1, 1, 32u, 864u },
    /* GroupNorm_0/bias                                     */ { 32, 1, 1, 1, 32u, 896u },
    /* Conv_1/kernel                                        */ { 1, 3, 1, 32, 96u, 928u },
    /* GroupNorm_1/scale                                    */ { 32, 1, 1, 1, 32u, 1024u },
    /* GroupNorm_1/bias                                     */ { 32, 1, 1, 1, 32u, 1056u },
    /* Conv_2/kernel                                        */ { 3, 3, 32, 48, 13824u, 1088u },
    /* GroupNorm_2/scale                                    */ { 48, 1, 1, 1, 48u, 14912u },
    /* GroupNorm_2/bias                                     */ { 48, 1, 1, 1, 48u, 14960u },
    /* Conv_3/kernel                                        */ { 1, 48, 1, 1, 48u, 15008u },
    /* RelConformerBlock_0/LayerNorm_0/scale                */ { 48, 1, 1, 1, 48u, 15056u },
    /* RelConformerBlock_0/LayerNorm_0/bias                 */ { 48, 1, 1, 1, 48u, 15104u },
    /* RelConformerBlock_0/RelPosSelfAttention_0/Dense_0/kernel */ { 48, 144, 1, 1, 6912u, 15152u },
    /* RelConformerBlock_0/RelPosSelfAttention_0/Dense_0/bias */ { 144, 1, 1, 1, 144u, 22064u },
    /* RelConformerBlock_0/RelPosSelfAttention_0/rel_bias   */ { 97, 4, 1, 1, 388u, 22208u },
    /* RelConformerBlock_0/RelPosSelfAttention_0/Dense_1/kernel */ { 48, 48, 1, 1, 2304u, 22596u },
    /* RelConformerBlock_0/RelPosSelfAttention_0/Dense_1/bias */ { 48, 1, 1, 1, 48u, 24900u },
    /* RelConformerBlock_0/LayerNorm_1/scale                */ { 48, 1, 1, 1, 48u, 24948u },
    /* RelConformerBlock_0/LayerNorm_1/bias                 */ { 48, 1, 1, 1, 48u, 24996u },
    /* RelConformerBlock_0/Conv_0/kernel                    */ { 3, 1, 48, 1, 144u, 25044u },
    /* RelConformerBlock_0/Conv_1/kernel                    */ { 7, 1, 48, 1, 336u, 25188u },
    /* RelConformerBlock_0/Conv_2/kernel                    */ { 1, 48, 48, 1, 2304u, 25524u },
    /* RelConformerBlock_0/Dense_0/kernel                   */ { 48, 6, 1, 1, 288u, 27828u },
    /* RelConformerBlock_0/Dense_1/kernel                   */ { 6, 48, 1, 1, 288u, 28116u },
    /* RelConformerBlock_0/LayerNorm_2/scale                */ { 48, 1, 1, 1, 48u, 28404u },
    /* RelConformerBlock_0/LayerNorm_2/bias                 */ { 48, 1, 1, 1, 48u, 28452u },
    /* RelConformerBlock_0/Dense_2/kernel                   */ { 48, 96, 1, 1, 4608u, 28500u },
    /* RelConformerBlock_0/Dense_2/bias                     */ { 96, 1, 1, 1, 96u, 33108u },
    /* RelConformerBlock_0/Dense_3/kernel                   */ { 96, 48, 1, 1, 4608u, 33204u },
    /* RelConformerBlock_0/Dense_3/bias                     */ { 48, 1, 1, 1, 48u, 37812u },
    /* RelConformerBlock_1/LayerNorm_0/scale                */ { 48, 1, 1, 1, 48u, 37860u },
    /* RelConformerBlock_1/LayerNorm_0/bias                 */ { 48, 1, 1, 1, 48u, 37908u },
    /* RelConformerBlock_1/RelPosSelfAttention_0/Dense_0/kernel */ { 48, 144, 1, 1, 6912u, 37956u },
    /* RelConformerBlock_1/RelPosSelfAttention_0/Dense_0/bias */ { 144, 1, 1, 1, 144u, 44868u },
    /* RelConformerBlock_1/RelPosSelfAttention_0/rel_bias   */ { 97, 4, 1, 1, 388u, 45012u },
    /* RelConformerBlock_1/RelPosSelfAttention_0/Dense_1/kernel */ { 48, 48, 1, 1, 2304u, 45400u },
    /* RelConformerBlock_1/RelPosSelfAttention_0/Dense_1/bias */ { 48, 1, 1, 1, 48u, 47704u },
    /* RelConformerBlock_1/LayerNorm_1/scale                */ { 48, 1, 1, 1, 48u, 47752u },
    /* RelConformerBlock_1/LayerNorm_1/bias                 */ { 48, 1, 1, 1, 48u, 47800u },
    /* RelConformerBlock_1/Conv_0/kernel                    */ { 3, 1, 48, 1, 144u, 47848u },
    /* RelConformerBlock_1/Conv_1/kernel                    */ { 7, 1, 48, 1, 336u, 47992u },
    /* RelConformerBlock_1/Conv_2/kernel                    */ { 1, 48, 48, 1, 2304u, 48328u },
    /* RelConformerBlock_1/Dense_0/kernel                   */ { 48, 6, 1, 1, 288u, 50632u },
    /* RelConformerBlock_1/Dense_1/kernel                   */ { 6, 48, 1, 1, 288u, 50920u },
    /* RelConformerBlock_1/LayerNorm_2/scale                */ { 48, 1, 1, 1, 48u, 51208u },
    /* RelConformerBlock_1/LayerNorm_2/bias                 */ { 48, 1, 1, 1, 48u, 51256u },
    /* RelConformerBlock_1/Dense_2/kernel                   */ { 48, 96, 1, 1, 4608u, 51304u },
    /* RelConformerBlock_1/Dense_2/bias                     */ { 96, 1, 1, 1, 96u, 55912u },
    /* RelConformerBlock_1/Dense_3/kernel                   */ { 96, 48, 1, 1, 4608u, 56008u },
    /* RelConformerBlock_1/Dense_3/bias                     */ { 48, 1, 1, 1, 48u, 60616u },
    /* RelConformerBlock_2/LayerNorm_0/scale                */ { 48, 1, 1, 1, 48u, 60664u },
    /* RelConformerBlock_2/LayerNorm_0/bias                 */ { 48, 1, 1, 1, 48u, 60712u },
    /* RelConformerBlock_2/RelPosSelfAttention_0/Dense_0/kernel */ { 48, 144, 1, 1, 6912u, 60760u },
    /* RelConformerBlock_2/RelPosSelfAttention_0/Dense_0/bias */ { 144, 1, 1, 1, 144u, 67672u },
    /* RelConformerBlock_2/RelPosSelfAttention_0/rel_bias   */ { 97, 4, 1, 1, 388u, 67816u },
    /* RelConformerBlock_2/RelPosSelfAttention_0/Dense_1/kernel */ { 48, 48, 1, 1, 2304u, 68204u },
    /* RelConformerBlock_2/RelPosSelfAttention_0/Dense_1/bias */ { 48, 1, 1, 1, 48u, 70508u },
    /* RelConformerBlock_2/LayerNorm_1/scale                */ { 48, 1, 1, 1, 48u, 70556u },
    /* RelConformerBlock_2/LayerNorm_1/bias                 */ { 48, 1, 1, 1, 48u, 70604u },
    /* RelConformerBlock_2/Conv_0/kernel                    */ { 3, 1, 48, 1, 144u, 70652u },
    /* RelConformerBlock_2/Conv_1/kernel                    */ { 7, 1, 48, 1, 336u, 70796u },
    /* RelConformerBlock_2/Conv_2/kernel                    */ { 1, 48, 48, 1, 2304u, 71132u },
    /* RelConformerBlock_2/Dense_0/kernel                   */ { 48, 6, 1, 1, 288u, 73436u },
    /* RelConformerBlock_2/Dense_1/kernel                   */ { 6, 48, 1, 1, 288u, 73724u },
    /* RelConformerBlock_2/LayerNorm_2/scale                */ { 48, 1, 1, 1, 48u, 74012u },
    /* RelConformerBlock_2/LayerNorm_2/bias                 */ { 48, 1, 1, 1, 48u, 74060u },
    /* RelConformerBlock_2/Dense_2/kernel                   */ { 48, 96, 1, 1, 4608u, 74108u },
    /* RelConformerBlock_2/Dense_2/bias                     */ { 96, 1, 1, 1, 96u, 78716u },
    /* RelConformerBlock_2/Dense_3/kernel                   */ { 96, 48, 1, 1, 4608u, 78812u },
    /* RelConformerBlock_2/Dense_3/bias                     */ { 48, 1, 1, 1, 48u, 83420u },
    /* SoftORStatsPool_0/Dense_0/kernel                     */ { 48, 24, 1, 1, 1152u, 83468u },
    /* SoftORStatsPool_0/Dense_0/bias                       */ { 24, 1, 1, 1, 24u, 84620u },
    /* SoftORStatsPool_0/or_w                               */ { 24, 1, 1, 1, 24u, 84644u },
    /* SoftORStatsPool_0/or_b                               */ { 1, 1, 1, 1, 1u, 84668u },
    /* Dense_0/kernel                                       */ { 97, 2, 1, 1, 194u, 84669u },
    /* Dense_0/bias                                         */ { 2, 1, 1, 1, 2u, 84863u },
};

/* Generated list length must equal KWS_NUM_TENSORS (76 here). */
_Static_assert(sizeof(kws_tensors) / sizeof(kws_tensors[0]) == KWS_NUM_TENSORS,
              "kws_tensors length != KWS_NUM_TENSORS; the enum in "
              "kws_model_data.h length != KWS_NUM_TENSORS; the enum "
              "in kws_model.h and export_weights.py have drifted");
