/*
 * GENERATED by tools/export_m1gw_weights.py -- do not edit.
 *
 * Source : best_m1g_wide.pt  (146,187 parameters)
 * Arch   : m1_g_wide
 * Frozen threshold: 0.796077
 *
 * Each tensor's dtype, shape, offset and scale count are fixed by the
 * exporter after checking them against the architecture, so the kernel
 * can index this table without knowing anything about the checkpoint.
 */

#ifndef KWS_M1GW_DATA_H
#define KWS_M1GW_DATA_H

#include <stdint.h>

#define KWS_M1GW_TENSOR_COUNT 57
#define KWS_M1GW_PARAM_COUNT 146187u
#define KWS_M1GW_SCALE_COUNT 2182u
#define KWS_M1GW_THRESHOLD 0.796077f

typedef enum {
    KWS_M1GW_T_STEM1_DW_WEIGHT = 0,
    KWS_M1GW_T_STEM1_NORM_WEIGHT = 1,
    KWS_M1GW_T_STEM1_NORM_BIAS = 2,
    KWS_M1GW_T_STEM1_PW_WEIGHT = 3,
    KWS_M1GW_T_DOWN_DW_WEIGHT = 4,
    KWS_M1GW_T_DOWN_NORM_WEIGHT = 5,
    KWS_M1GW_T_DOWN_NORM_BIAS = 6,
    KWS_M1GW_T_DOWN_PW_WEIGHT = 7,
    KWS_M1GW_T_STEM2_DW_WEIGHT = 8,
    KWS_M1GW_T_STEM2_NORM_WEIGHT = 9,
    KWS_M1GW_T_STEM2_NORM_BIAS = 10,
    KWS_M1GW_T_STEM2_PW_WEIGHT = 11,
    KWS_M1GW_T_MEL_GATE_FC1_WEIGHT = 12,
    KWS_M1GW_T_MEL_GATE_FC1_BIAS = 13,
    KWS_M1GW_T_MEL_GATE_FC2_WEIGHT = 14,
    KWS_M1GW_T_BLOCKS_0_NORM1_WEIGHT = 15,
    KWS_M1GW_T_BLOCKS_0_NORM1_BIAS = 16,
    KWS_M1GW_T_BLOCKS_0_ATTN_REL_BIAS = 17,
    KWS_M1GW_T_BLOCKS_0_ATTN_QKV_WEIGHT = 18,
    KWS_M1GW_T_BLOCKS_0_ATTN_QKV_BIAS = 19,
    KWS_M1GW_T_BLOCKS_0_ATTN_PROJ_WEIGHT = 20,
    KWS_M1GW_T_BLOCKS_0_ATTN_PROJ_BIAS = 21,
    KWS_M1GW_T_BLOCKS_0_NORM2_WEIGHT = 22,
    KWS_M1GW_T_BLOCKS_0_NORM2_BIAS = 23,
    KWS_M1GW_T_BLOCKS_0_DW_0_WEIGHT = 24,
    KWS_M1GW_T_BLOCKS_0_DW_1_WEIGHT = 25,
    KWS_M1GW_T_BLOCKS_0_PW_WEIGHT = 26,
    KWS_M1GW_T_BLOCKS_0_SE_FC1_WEIGHT = 27,
    KWS_M1GW_T_BLOCKS_0_SE_FC2_WEIGHT = 28,
    KWS_M1GW_T_BLOCKS_0_NORM3_WEIGHT = 29,
    KWS_M1GW_T_BLOCKS_0_NORM3_BIAS = 30,
    KWS_M1GW_T_BLOCKS_0_FF1_WEIGHT = 31,
    KWS_M1GW_T_BLOCKS_0_FF1_BIAS = 32,
    KWS_M1GW_T_BLOCKS_0_FF2_WEIGHT = 33,
    KWS_M1GW_T_BLOCKS_0_FF2_BIAS = 34,
    KWS_M1GW_T_BLOCKS_1_NORM1_WEIGHT = 35,
    KWS_M1GW_T_BLOCKS_1_NORM1_BIAS = 36,
    KWS_M1GW_T_BLOCKS_1_ATTN_REL_BIAS = 37,
    KWS_M1GW_T_BLOCKS_1_ATTN_QKV_WEIGHT = 38,
    KWS_M1GW_T_BLOCKS_1_ATTN_QKV_BIAS = 39,
    KWS_M1GW_T_BLOCKS_1_ATTN_PROJ_WEIGHT = 40,
    KWS_M1GW_T_BLOCKS_1_ATTN_PROJ_BIAS = 41,
    KWS_M1GW_T_BLOCKS_1_NORM2_WEIGHT = 42,
    KWS_M1GW_T_BLOCKS_1_NORM2_BIAS = 43,
    KWS_M1GW_T_BLOCKS_1_DW_0_WEIGHT = 44,
    KWS_M1GW_T_BLOCKS_1_DW_1_WEIGHT = 45,
    KWS_M1GW_T_BLOCKS_1_PW_WEIGHT = 46,
    KWS_M1GW_T_BLOCKS_1_SE_FC1_WEIGHT = 47,
    KWS_M1GW_T_BLOCKS_1_SE_FC2_WEIGHT = 48,
    KWS_M1GW_T_BLOCKS_1_NORM3_WEIGHT = 49,
    KWS_M1GW_T_BLOCKS_1_NORM3_BIAS = 50,
    KWS_M1GW_T_BLOCKS_1_FF1_WEIGHT = 51,
    KWS_M1GW_T_BLOCKS_1_FF1_BIAS = 52,
    KWS_M1GW_T_BLOCKS_1_FF2_WEIGHT = 53,
    KWS_M1GW_T_BLOCKS_1_FF2_BIAS = 54,
    KWS_M1GW_T_HEAD_WEIGHT = 55,
    KWS_M1GW_T_HEAD_BIAS = 56,
} kws_m1gw_tensor_id;

typedef struct {
    /* offset and scale_off are uint32_t. Both tables outgrow 16 bits on
     * this checkpoint (159,651 weight elements, 2,182 scales), and a
     * truncating initializer is a silent mis-read, not a build error on
     * the target toolchain. */
    uint32_t offset;     /* BYTE offset into the blob -- both Ti() and Tf()
     *                            add it to an int8_t pointer, which advances in
     *                            bytes. Storing an ELEMENT index here instead made
     *                            Tf() read 4x too early and the network returned
     *                            NaN rather than a wrong number. */
    uint32_t count;      /* elements                              */
    uint32_t scale_off;  /* first scale in kws_m1gw_scales        */
    uint16_t scale_n;    /* 0 = float32 tensor, no scales         */
    uint16_t is_f32;
    uint8_t  ndim;
    uint8_t  pad;
    uint16_t dim[4];
} kws_m1gw_tensor;

extern const kws_m1gw_tensor kws_m1gw_tensors[KWS_M1GW_TENSOR_COUNT];

/* Non-const pointers to const data so the host harness can rebind them
 * to heap copies; the firmware binds them to the generated arrays. Both
 * link the same inference code, so a host pass is a real pass. */
extern const int8_t  *kws_m1gw_blob;
extern const float   *kws_m1gw_scales;

#endif /* KWS_M1GW_DATA_H */
