"""
Convert a flat float32 blob into a C source file with an aligned array.

Why not use CMake EMBED_FILES? A blob placed into .rodata by the assembler has
no guaranteed 4-byte alignment, and the Xtensa LX7 traps on unaligned float
loads rather than silently working. Emitting a C array lets the compiler place
it with explicit alignment, so the weights are always safe to read as float*.

Generated output is in the repository's build tree, not the source tree, so the
binary stays the single committed artefact.

Usage:  python tools/bin2c.py <input.bin> <output.c> <symbol>
"""

import struct
import sys


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 1

    src, dst, sym = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src, "rb") as f:
        raw = f.read()

    if len(raw) % 4:
        raise SystemExit(f"{src}: {len(raw)} bytes is not a multiple of 4")

    n = len(raw) // 4
    vals = struct.unpack(f"<{n}f", raw)

    with open(dst, "w", newline="\n") as f:
        f.write("/* Generated by tools/bin2c.py - do not edit. */\n")
        f.write(f"/* source: {src}  {n} float32 values ({len(raw)} bytes) */\n")
        f.write('#include <stdint.h>\n\n')
        # 16-byte alignment: the largest load the model performs is float32, but
        # this also keeps the array friendly to any future SIMD kernel.
        f.write(f'__attribute__((aligned(16))) const float {sym}[{n}] = {{\n')

        per_line = 8
        for i in range(0, n, per_line):
            chunk = vals[i:i + per_line]
            # %a keeps every value exact and round-trips bit-for-bit.
            body = ", ".join(float.hex(v) for v in chunk)
            f.write(f"    {body},\n")

        f.write("};\n")

    print(f"bin2c: {src} -> {dst}  ({n} floats)")
    return 0


if __name__ == "__main__":
    sys.exit(main())