"""
Convert a flat weight blob into a C source file with an aligned array.

Why not use CMake EMBED_FILES? A blob placed into .rodata by the assembler has
no guaranteed 4-byte alignment, and the Xtensa LX7 traps on unaligned loads
rather than silently working. Emitting a C array lets the compiler place it with
explicit alignment.

For the INT8 weights that matters for a second reason: the vector reduction in
main/kws_xtensa.S loads 128 bits at a time, and tools/export_weights.py pads every
tensor to a 16-byte boundary, so the array has to be 16-byte aligned too or
every first row is one load out of place.

Generated output is in the repository's build tree, not the source tree, so the
binary stays the single committed artefact.

Usage:
    python tools/bin2c.py <input.bin> <output.c> <symbol> [--int8]
"""

import struct
import sys


def main():
    args = [a for a in sys.argv[1:] if a != "--int8"]
    as_int8 = "--int8" in sys.argv[1:]

    if len(args) != 3:
        print(__doc__)
        return 1

    src, dst, sym = args

    with open(src, "rb") as f:
        raw = f.read()

    if as_int8:
        # int8 needs 16-byte alignment and nothing else: the vector loads want
        # it, and a trailing pad of zero is a legal weight.
        if not raw:
            raw = b"\x00" * 16
        if len(raw) % 16:
            raise SystemExit(
                f"{src}: {len(raw)} bytes; pad the blob to a multiple of 16 in "
                f"tools/export_weights.py rather than here")
        with open(dst, "w", newline="\n") as f:
            f.write("/* Generated by tools/bin2c.py - do not edit. */\n")
            f.write(f"/* source: {src}  {len(raw)} int8 values */\n")
            f.write('#include <stdint.h>\n\n')
            f.write(f"__attribute__((aligned(16))) const int8_t {sym}"
                    f"[{len(raw)}] = {{\n")
            per_line = 32
            for i in range(0, len(raw), per_line):
                body = ", ".join(str(b if b < 128 else b - 256)
                                 for b in raw[i:i + per_line])
                f.write(f"    {body},\n")
            f.write("};\n")
        print(f"bin2c: {src} -> {dst}  ({len(raw)} int8)")
        return 0

    if len(raw) % 4:
        raise SystemExit(f"{src}: {len(raw)} bytes is not a multiple of 4")

    n = len(raw) // 4
    vals = struct.unpack(f"<{n}f", raw)

    with open(dst, "w", newline="\n") as f:
        f.write("/* Generated by tools/bin2c.py - do not edit. */\n")
        f.write(f"/* source: {src}  {n} float32 values ({len(raw)} bytes) */\n")
        f.write('#include <stdint.h>\n\n')
        # 16-byte alignment: the largest load the model performs is float32, but
        # this also keeps the array friendly to any future SIMD kernel.
        f.write(f'__attribute__((aligned(16))) const float {sym}[{n}] = {{\n')

        per_line = 8
        for i in range(0, n, per_line):
            chunk = vals[i:i + per_line]
            # %a keeps every value exact and round-trips bit-for-bit.
            body = ", ".join(float.hex(v) for v in chunk)
            f.write(f"    {body},\n")

        f.write("};\n")

    print(f"bin2c: {src} -> {dst}  ({n} floats)")
    return 0


if __name__ == "__main__":
    sys.exit(main())